### ISSUE TITLE
Invoke-FreeIPAAPIpasswd - Password Error

### ISSUE THREAD

**Issue by nadinezan** [MS-LUF/Manage-FreeIPA#1]
Hello, 

thanks a lot for this awesome work. 
I found an error in the function Invoke-FreeIPAAPIpasswd  

```
Cannot convert the "myFancyPassword" value of type "System.String" to type System.Security.SecureString".
At /root/Manage-FreeIPA/Manage-FreeIPA.psm1:22190 char:25
+ ... password) { $password = [Runtime.InteropServices.Marshal]::PtrToStrin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
+ FullyQualifiedErrorId : RuntimeException
```
$otp, $password and $current_password are defined in the param section as SecureString and overwritten as String in Lines 22189, 22190 and 22191, which throws the error.

Workaround: Change parameter names (e.g. $otp1, $password1, $current_password1)

```
if ($otp) { $otp1 = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($otp)) }
       if ($password) { $password1 = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($password)) }
       if ($current_password) { $current_password1 = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($current_password)) }
       if ($otp) { $ObjParams | Add-Member -NotePropertyName otp -NotePropertyValue $otp1 }

        $JsonObject = New-Object psobject -property @{
                id		= 0
                method	= "passwd/1"
                params  = @(@($user,$password1,$current_password1),$ObjParams)
            }
```

Best regards,

Nadine

**Comment by MS-LUF** [comment]
Hello Nadine,
Thanks for the feedback. 
Quite interesting to see that my work can help others :)
I will include your fix in the next build of Build-FreeIPAModule and then build a new release of Manage-FreeIPA.
Do you know if this module works well with the last build of FreeIPA ?

**Comment by MS-LUF** [comment]
Hello Nadine,
Fix in last release published today.
For your info it was just a matter of object type issue. It s not necessary to duplicate the variable. Just force [string] type because the type was previously set as a parameter.
